/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tugas4;

import javax.swing.JOptionPane;

/**
 *
 * @author MAULANA
 */
public class pesananForm extends javax.swing.JInternalFrame {

    /** Creates new form pesananForm */
    public pesananForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tableNumberTxt = new javax.swing.JTextField();
        riceCbx = new javax.swing.JComboBox<>();
        cookCbx = new javax.swing.JComboBox<>();
        drinkCbx = new javax.swing.JComboBox<>();
        riceTxt = new javax.swing.JTextField();
        cookTxt = new javax.swing.JTextField();
        drinkTxt = new javax.swing.JTextField();
        riceAmountTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cookAmountTxt = new javax.swing.JTextField();
        drinkAmountTxt = new javax.swing.JTextField();
        ricePurchaseTxt = new javax.swing.JTextField();
        cookPurchaseTxt = new javax.swing.JTextField();
        drinkPurchaseTxt = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        totalPurchaseAmountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("PESANAN");
        setVisible(true);

        jLabel1.setText("NO. MEJA");

        jLabel2.setText("HARGA");

        tableNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNumberTxtActionPerformed(evt);
            }
        });

        riceCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paket 1", "Nasi Puti ", "Nasi Goreng", "Nasi Capcay" }));
        riceCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceCbxActionPerformed(evt);
            }
        });

        cookCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paket 2", "Ayam Penyet", "Ayam Bakar", "Ayam Goreng" }));
        cookCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookCbxActionPerformed(evt);
            }
        });

        drinkCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paket 3", "Aqua", "Jus Alpukat", "Jus Jeruk" }));
        drinkCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkCbxActionPerformed(evt);
            }
        });

        riceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        riceTxt.setText("0");
        riceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceTxtActionPerformed(evt);
            }
        });

        cookTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cookTxt.setText("0");

        drinkTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        drinkTxt.setText("0");

        riceAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        riceAmountTxt.setText("0");

        jLabel3.setText("JUML BELI");

        jLabel4.setText("BAYAR");

        cookAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cookAmountTxt.setText("0");

        drinkAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        drinkAmountTxt.setText("0");
        drinkAmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkAmountTxtActionPerformed(evt);
            }
        });

        ricePurchaseTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ricePurchaseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ricePurchaseTxtActionPerformed(evt);
            }
        });

        cookPurchaseTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        drinkPurchaseTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        payButton.setText("BAYAR");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        totalPurchaseAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("TOTAL PESANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(riceCbx, 0, 113, Short.MAX_VALUE)
                            .addComponent(cookCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drinkCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cookTxt)
                                .addComponent(drinkTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(riceTxt))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drinkAmountTxt)
                                    .addComponent(cookAmountTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cookPurchaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drinkPurchaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(riceAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ricePurchaseTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(payButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(totalPurchaseAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableNumberTxt)
                    .addComponent(okButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ricePurchaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riceAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riceCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cookTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookPurchaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drinkCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkPurchaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPurchaseAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(payButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceTxtActionPerformed

    private void tableNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumberTxtActionPerformed

    private void ricePurchaseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ricePurchaseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ricePurchaseTxtActionPerformed

    private void drinkAmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkAmountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkAmountTxtActionPerformed

    private void riceCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceCbxActionPerformed
        switch(riceCbx.getSelectedIndex()){
            case 0:
                riceTxt.setText("0");
                riceAmountTxt.setText("0");
                break;
            case 1:
                riceTxt.setText("5000");
                riceAmountTxt.setText("");
                break;
                case 2:
                riceTxt.setText("9000");
                riceAmountTxt.setText("");
                break;
            default:
                riceTxt.setText("10000");
                riceAmountTxt.setText("");
                break;
        }
    }//GEN-LAST:event_riceCbxActionPerformed

    private void cookCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookCbxActionPerformed
        switch(cookCbx.getSelectedIndex()){
            case 0:
                cookTxt.setText("0");
                cookAmountTxt.setText("0");
                break;
            case 1:
                cookTxt.setText("8000");
                cookAmountTxt.setText("");
                break;
            case 2:
                cookTxt.setText("9000");
                cookAmountTxt.setText("");
                break;
            default:
                cookTxt.setText("10000");
                cookAmountTxt.setText("");
                break;
        }
    }//GEN-LAST:event_cookCbxActionPerformed

    private void drinkCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkCbxActionPerformed
        switch(drinkCbx.getSelectedIndex()){
            case 0:
                drinkTxt.setText("0");
                drinkAmountTxt.setText("0");
                break;
            case 1:
                drinkTxt.setText("3000");
                drinkAmountTxt.setText("");
                break;
            case 2:
                drinkTxt.setText("6000");
                drinkAmountTxt.setText("");
                break;
            default:
                drinkTxt.setText("7000");
                drinkAmountTxt.setText("");
                break;
        }
    }//GEN-LAST:event_drinkCbxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(riceTxt.getText().isEmpty()|| riceAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi pesanan paket 1");
        }else if(cookTxt.getText().isEmpty() || cookAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi pesanan paket 2");
        }else if(drinkTxt.getText().isEmpty() || drinkAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi pesanan paket 3");
        }else {
            double ricePrice = Double.parseDouble(riceTxt.getText()),
                    cookPrice = Double.parseDouble(cookTxt.getText()),
                    drinkPrice = Double.parseDouble(drinkTxt.getText()),
                    riceAmount = Double.parseDouble(riceAmountTxt.getText()),
                    cookAmount = Double.parseDouble(cookAmountTxt.getText()),
                    drinkAmount = Double.parseDouble(drinkAmountTxt.getText()),
                    totalRice, totalCook, totalDrink, totalPurchaseAmount;
            
            totalRice = ricePrice * riceAmount;
            totalCook = cookPrice * cookAmount;
            totalDrink = drinkPrice * drinkAmount;
            totalPurchaseAmount = totalRice + totalCook + totalDrink;
            
            ricePurchaseTxt.setText("" + totalRice);
            cookPurchaseTxt.setText("" + totalCook);
            drinkPurchaseTxt.setText("" + totalDrink);
            totalPurchaseAmountTxt.setText("" + totalPurchaseAmount);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        if(totalPurchaseAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Tekan tombol OK terlebih dahulu");
        }else {
            bayarForm bayarform = new bayarForm(tableNumberTxt.getText(),totalPurchaseAmountTxt.getText());
            bayarform.setVisible(true);
            this.getDesktopPane().add(bayarform);
            this.dispose();
        }
    }//GEN-LAST:event_payButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cookAmountTxt;
    private javax.swing.JComboBox<String> cookCbx;
    private javax.swing.JTextField cookPurchaseTxt;
    private javax.swing.JTextField cookTxt;
    private javax.swing.JTextField drinkAmountTxt;
    private javax.swing.JComboBox<String> drinkCbx;
    private javax.swing.JTextField drinkPurchaseTxt;
    private javax.swing.JTextField drinkTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okButton;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField riceAmountTxt;
    private javax.swing.JComboBox<String> riceCbx;
    private javax.swing.JTextField ricePurchaseTxt;
    private javax.swing.JTextField riceTxt;
    private javax.swing.JTextField tableNumberTxt;
    private javax.swing.JTextField totalPurchaseAmountTxt;
    // End of variables declaration//GEN-END:variables

}
